# Generated by Django 3.0.8 on 2020-07-13 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamondtrails', '0002_statusupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusupdate',
            name='message',
            field=models.CharField(default='other', max_length=200),
            preserve_default=False,
        ),
    ]
