# Generated by Django 3.0.8 on 2020-07-13 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamondtrails', '0003_statusupdate_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusupdate',
            name='external_id',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
