# Generated by Django 3.0.8 on 2020-07-13 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamondtrails', '0004_statusupdate_external_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='uid',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
