# Generated by Django 3.0.8 on 2020-07-13 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamondtrails', '0005_user_uid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_id', models.BigIntegerField()),
                ('phone', models.CharField(max_length=15)),
            ],
        ),
    ]
