# Generated by Django 3.0.8 on 2020-07-13 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamondtrails', '0006_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='USstate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('abbr', models.CharField(max_length=2)),
                ('lat', models.DecimalField(decimal_places=16, max_digits=22)),
                ('lng', models.DecimalField(decimal_places=16, max_digits=22)),
            ],
        ),
    ]
