# Generated by Django 3.0.8 on 2020-07-14 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamondtrails', '0007_usstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='trail',
            field=models.CharField(default='Test', max_length=150),
            preserve_default=False,
        ),
    ]
