# Generated by Django 3.0.2 on 2020-07-16 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diamondtrails', '0008_subscription_trail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
